### ISSUE TITLE
Cash App Pay Button - Second time open model Regenerate issue

### ISSUE THREAD

**Issue by bhavinangular28** [square/web-sdk#162]
I have implemented the model for one, but the second time when the model is opened, it doesn't regenerate. Without a page refresh function
![Screenshot_1](https://user-images.githubusercontent.com/125279136/234567016-33cd3bcd-586d-4d3e-a297-4542c3fefa6c.png)

**Comment by maxbeatty** [comment]
This is likely an implementation issue rather than a bug with this repository. Would you mind posting to our [Developer forums](https://developer.squareup.com/forums/tag/web-payments-sdk) where we're able to give better support for cases like this? A minimal reproduction for how you are building your experience would also be helpful. If you aren't already, you might call [detach](https://developer.squareup.com/reference/sdks/web/payments/cash-app-pay#CashAppPay.detach) (or destroy) when your model (modal?) is closed. Then, you should be able to attach again the second time.
